2025-03-18 17:29:41,326 - masking_service - ERROR - SpaCy modeli yüklenirken hata: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a Python package or a valid path to a data directory.
2025-03-18 17:31:09,206 - custom_entities - INFO - Özel varlýk tanýyýcýlar baþarýyla eklendi
2025-03-18 17:31:09,207 - masking_service - INFO - SpaCy modeli ve özel varlýk desenleri baþarýyla yüklendi
2025-03-18 17:31:09,210 - __main__ - INFO - Kiþisel veri maskeleme servisi baþlatýlýyor...
2025-03-18 17:31:09,246 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.89:5000
2025-03-18 17:31:09,247 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-03-18 17:32:20,745 - masking_service - ERROR - Maskeleme iþlemi sýrasýnda hata: [E1010] Unable to set entity information for token 170 which is included in more than one span in entities, blocked, missing or outside.
Traceback (most recent call last):
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\masking_service.py", line 46, in mask_personal_data
    doc = self.nlp(text)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1031, in __call__
    error_handler(name, proc, [doc], e)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\util.py", line 1670, in raise_error
    raise e
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1026, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\custom_entities.py", line 118, in __call__
    doc.ents = list(doc.ents) + spans
  File "spacy\tokens\doc.pyx", line 762, in spacy.tokens.doc.Doc.ents.__set__
  File "spacy\tokens\doc.pyx", line 799, in spacy.tokens.doc.Doc.set_ents
ValueError: [E1010] Unable to set entity information for token 170 which is included in more than one span in entities, blocked, missing or outside.
2025-03-18 17:32:20,799 - werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 17:32:20] "POST /mask_text HTTP/1.1" 200 -
2025-03-18 17:33:38,334 - masking_service - ERROR - Maskeleme iþlemi sýrasýnda hata: [E1010] Unable to set entity information for token 98 which is included in more than one span in entities, blocked, missing or outside.
Traceback (most recent call last):
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\masking_service.py", line 46, in mask_personal_data
    doc = self.nlp(text)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1031, in __call__
    error_handler(name, proc, [doc], e)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\util.py", line 1670, in raise_error
    raise e
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1026, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\custom_entities.py", line 150, in __call__
    doc.ents = list(doc.ents) + spans
  File "spacy\tokens\doc.pyx", line 762, in spacy.tokens.doc.Doc.ents.__set__
  File "spacy\tokens\doc.pyx", line 799, in spacy.tokens.doc.Doc.set_ents
ValueError: [E1010] Unable to set entity information for token 98 which is included in more than one span in entities, blocked, missing or outside.
2025-03-18 17:33:38,337 - werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 17:33:38] "POST /mask_text HTTP/1.1" 200 -
2025-03-18 17:36:48,720 - custom_entities - INFO - Özel varlýk tanýyýcýlar baþarýyla eklendi
2025-03-18 17:36:48,720 - masking_service - INFO - SpaCy modeli ve özel varlýk desenleri baþarýyla yüklendi
2025-03-18 17:36:48,721 - __main__ - INFO - Kiþisel veri maskeleme servisi baþlatýlýyor...
2025-03-18 17:36:48,734 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.89:5000
2025-03-18 17:36:48,734 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-03-18 17:37:01,646 - masking_service - ERROR - Maskeleme iþlemi sýrasýnda hata: [E1010] Unable to set entity information for token 98 which is included in more than one span in entities, blocked, missing or outside.
Traceback (most recent call last):
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\masking_service.py", line 46, in mask_personal_data
    doc = self.nlp(text)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1031, in __call__
    error_handler(name, proc, [doc], e)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\util.py", line 1670, in raise_error
    raise e
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1026, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\custom_entities.py", line 200, in __call__
    doc.ents = list(doc.ents) + spans
  File "spacy\tokens\doc.pyx", line 762, in spacy.tokens.doc.Doc.ents.__set__
  File "spacy\tokens\doc.pyx", line 799, in spacy.tokens.doc.Doc.set_ents
ValueError: [E1010] Unable to set entity information for token 98 which is included in more than one span in entities, blocked, missing or outside.
2025-03-18 17:37:01,656 - werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 17:37:01] "POST /mask_text HTTP/1.1" 200 -
2025-03-18 17:41:46,195 - masking_service - ERROR - Maskeleme iþlemi sýrasýnda hata: [E1010] Unable to set entity information for token 98 which is included in more than one span in entities, blocked, missing or outside.
Traceback (most recent call last):
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\masking_service.py", line 46, in mask_personal_data
    doc = self.nlp(text)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1031, in __call__
    error_handler(name, proc, [doc], e)
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\util.py", line 1670, in raise_error
    raise e
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\venv\lib\site-packages\spacy\language.py", line 1026, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "C:\Users\emrea\Desktop\Yazlab2-1\AnonService\custom_entities.py", line 200, in __call__
    doc.ents = list(doc.ents) + spans
  File "spacy\tokens\doc.pyx", line 762, in spacy.tokens.doc.Doc.ents.__set__
  File "spacy\tokens\doc.pyx", line 799, in spacy.tokens.doc.Doc.set_ents
ValueError: [E1010] Unable to set entity information for token 98 which is included in more than one span in entities, blocked, missing or outside.
2025-03-18 17:42:50,521 - werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 17:42:50] "POST /mask_text HTTP/1.1" 200 -
2025-03-18 17:42:54,965 - __main__ - INFO - Kiþisel veri maskeleme servisi baþlatýlýyor...
2025-03-18 17:42:54,985 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.43.89:5000
2025-03-18 17:42:54,985 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-03-18 17:43:02,209 - werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 17:43:02] "POST /mask_text HTTP/1.1" 200 -
2025-03-18 17:43:23,469 - werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 17:43:23] "POST /mask_text HTTP/1.1" 200 -
